version: '3.7'

services:
  jenkins:
    build:
      context: ./
      dockerfile: ./dockerfile
    ports:
      - "8090:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  ssh-agent:
    image: jenkins/ssh-agent
    restart: unless-stopped
volumes:
  jenkins_home:
